### ISSUE TITLE
Example from README does not successfully run

### ISSUE THREAD

**Issue by sjvrijn** [ECOLE-ITN/NguyenSSCI2021#6]
## Issue

After the update to fix issue #3, the example in the README still does not run without issue.

Using the same setup as in #3, I first get this `ModuleNotFoundError`:
```
$ python example.py 
Traceback (most recent call last):
  File "/home/sander/src/bo4ml/example.py", line 43, in <module>
    from imblearn.over_sampling import SMOTE, BorderlineSMOTE
ModuleNotFoundError: No module named 'imblearn'
```

After installing this using `pip install imblearn`, another error occurs:
```
$ python example.py 
Traceback (most recent call last):
  File "/home/sander/src/bo4ml/example.py", line 85, in <module>
    opt = BO4ML(search_space, obj_func, 
  File "/home/sander/.pyenv/versions/bo4ml/lib/python3.9/site-packages/BanditOpt/BO4ML.py", line 135, in __init__
    _LstHPOsearchspace, _spRatio = ForFullSampling(search_space._hyperparameters, conditional, hpo_prefix,
  File "/home/sander/.pyenv/versions/bo4ml/lib/python3.9/site-packages/BanditOpt/HyperoptConverter.py", line 197, in ForFullSampling
    _max_sp = int(np.floor(max_eval * _defratio) / sample_sp) if _defratio != None else int(np.floor(init_sample / sample_sp))
TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'
```

**Comment by anh05** [comment]
@sjvrijn:  Thank you so much for your comment. My apologies for this inconvenience. The README is updated, and a jupyter notebook for this is also uploaded at: https://github.com/ECOLE-ITN/BO4ML/blob/assets/Example/BO4ML_simpleexample.ipynb
